# Generated by Django 3.2.20 on 2023-07-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_user_post_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
