# Generated by Django 3.2.20 on 2023-07-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_user_id_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
