# Generated by Django 3.2.20 on 2023-07-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20230722_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destination_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='source_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
